import {
  PiggyBank,
  HeartPulse,
  Sigma,
  Dumbbell,
  HardHat,
  FunctionSquare,
  Calculator as CalculatorIcon,
  Cake,
  Droplets,
  Building,
  Home,
  Landmark,
  Car,
  TrendingUp,
  LineChart,
  CalendarClock,
  Wallet,
  AreaChart,
  Receipt,
  Flame,
  Baby,
  PersonStanding,
  Minus,
  Percent,
  Divide,
  FlaskConical,
  Shuffle,
  ArrowRightLeft,
  Footprints,
  Briefcase,
  GitCommit,
  Wrench,
  KeyRound,
  HandCoins,
  Table,
  CarFront,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

// We can't store functions (React components) in Firestore,
// so we map the icon string from the DB to the actual component here.
export const calculatorIcons: { [key: string]: LucideIcon } = {
  PiggyBank,
  HeartPulse,
  Sigma,
  Dumbbell,
  HardHat,
  FunctionSquare,
  default: CalculatorIcon,
  Cake,
  Droplets,
  Building,
  Home,
  Landmark,
  Car,
  TrendingUp,
  LineChart,
  CalendarClock,
  Wallet,
  AreaChart,
  Receipt,
  Flame,
  Baby,
  PersonStanding,
  Minus,
  Percent,
  Divide,
  FlaskConical,
  Shuffle,
  ArrowRightLeft,
  Footprints,
  Briefcase,
  GitCommit,
  Wrench,
  KeyRound,
  HandCoins,
  Table,
  CarFront,
};
